- name: create swiftarr python virtualenv
  command: python3 -m venv /opt/swiftarr/venv
  args:
    creates: /opt/swiftarr/venv/bin/activate
  become: yes

- name: install python dependencies into swiftarr venv
  pip:
    requirements: "{{ twitarr_src_dir }}/requirements.txt"
    virtualenv: /opt/swiftarr/venv
    virtualenv_python: python3
  become: yes
